run_everything:
  image: nixos/nix
  variables:
    TZWITTER_L1_CONTRACT: "KT1..."
  script:
    - nix develop --experimental-features "nix-command flakes" --extra-substituters https://tezos.nix-cache.workers.dev  --extra-trusted-public-keys tezos-nix-cache.marigold.dev-1:4nS7FPPQPKJIaNQcbwzN6m7kylv16UCWWgjeZZr2wXA=  --command cargo make ci
