[workspace]

members = [
    "00_debug_kernel",
    "01_counter_kernel",
    # Disabled for now, because it doesn't compile.
    # "hello_kernel",
    # "output_kernel",
]

# FIXME: what is this? Do we need it?
[profile.release]
lto = true
opt-level = 's'
