[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.wasm-debug-kernel]
workspace = false
command = "cargo"
args = ["build", "-p", "debug-kernel",  "--release", "--target", "wasm32-unknown-unknown"]

[tasks.wasm-counter-kernel]
workspace = false
command = "cargo"
args = ["build", "-p", "counter-kernel", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.wasm-output-kernel]
workspace = false
command = "cargo"
args = ["build", "-p", "output-kernel", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.wasm-hello-kernel]
workspace = false
command = "cargo"
args = ["build", "-p", "hello-kernel", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.test]
workspace = false
command = "cargo"
args = ["test", "--features", "testing"]

[tasks.docs-test-clean]
workspace = false
command = "dune"
args = ["clean"]

[tasks.docs-test]
workspace = false
command = "dune"
args = ["runtest"]
dependencies = ["docs-test-clean", "wasm-debug-kernel", "wasm-counter-kernel" ]

[tasks.doc]
workspace = false
command = "cargo"
args = ["doc", "--features", "testing", "--no-deps", "--target-dir", "public"]

[tasks.ci]
workspace = false
dependencies = [
    "fmt", # FIXME: do we need both fmt and fmt-check here?
    "fmt-check",
    "wasm-debug-kernel",
    "wasm-counter-kernel",
    "docs-test"
    # FIXME: re-enable these when they compile
    # "wasm-output-kernel",
    # "wasm-hello-kernel",
    # "test",
    # "doc",
]