[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.wasm-debug-kernel]
workspace = false
command = "cargo"
args = ["build", "-p", "debug-kernel",  "--release", "--target", "wasm32-unknown-unknown"]

[tasks.wasm-counter-kernel]
workspace = false
command = "cargo"
args = ["build", "-p", "counter-kernel", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.wasm-output-kernel]
workspace = false
command = "cargo"
args = ["build", "-p", "output-kernel", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.test]
workspace = false
command = "cargo"
args = ["test", "--features", "testing"]

[tasks.doc]
workspace = false 
command = "cargo"
args = ["doc", "--features", "testing", "--no-deps", "--target-dir", "public"]

[tasks.ci]
workspace = false
dependencies = [
    "clean",
    "fmt",
    "fmt-check",
    "wasm-debug-kernel",
    "wasm-counter-kernel",
    "wasm-output-kernel",
    "test",
    "doc",
]