[package]
name = "outbox-kernel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
# getrandom = { version = "0.2", features = ["js"] }
serde = { version = "1.0", features = ["derive"] }
tezos_data_encoding = {version = "0.4"}
tezos_smart_rollup_core = { git = "https://gitlab.com/tezos/tezos" }
tezos_smart_rollup_host = { git = "https://gitlab.com/tezos/tezos" }
tezos_smart_rollup_debug = { git = "https://gitlab.com/tezos/tezos" }
tezos_smart_rollup_encoding = { git = "https://gitlab.com/tezos/tezos" }
tezos_smart_rollup_storage = { git = "https://gitlab.com/tezos/tezos" }
tezos_smart_rollup_entrypoint = { git = "https://gitlab.com/tezos/tezos" }
tezos_smart_rollup_mock = { git = "https://gitlab.com/tezos/tezos" }
tezos_crypto_rs = { version = "0.4", default-features = false }