name: Dungeon - sequencer docker

on:
  push:
    branches:
      - "dungeon-game"
    paths:
      - "10_dungeon/sequencer/**"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set image tag vars
        id: tag_vars
        run: |
          echo "date=$(date +%Y-%m-%dT%H-%M-%S)" >> "${GITHUB_OUTPUT}"
          echo "sha_short=$(git rev-parse --short HEAD)" >> "${GITHUB_OUTPUT}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace rl node endpoint
        id: sed
        run: |
          set -x
          sed -i 's|dungeon-sequencer.gcp.marigold.dev|dungeon-rollup-test1.gcp.marigold.dev|g' 10_dungeon/sequencer/sequencer-http/src/main.rs
          sed -i 's|127.0.0.1|0.0.0.0|g' 10_dungeon/sequencer/sequencer-http/src/main.rs
          cat 10_dungeon/sequencer/sequencer-http/src/main.rs

      - name: Copy Dockerfile and scripts
        id: copy
        run: |
          cp -r ./infra_tooling/docker/dungeon-sequencer-build/* 10_dungeon

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: ./10_dungeon/Dockerfile.sequencer
          context: ./10_dungeon/
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.ref == 'refs/heads/dungeon-game' }}
          tags: |
            ghcr.io/marigold-dev/dungeon-sequencer:latest
            ghcr.io/marigold-dev/dungeon-sequencer:${{ github.sha }}
            ghcr.io/marigold-dev/dungeon-sequencer:${{ steps.tag_vars.outputs.date }}-${{ steps.tag_vars.outputs.sha_short }}
