name: Dungeon - frontend docker

on:
  push:
    branches:
      - "dungeon-game"
    paths:
      - "10_dungeon/app/**"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace sequencer endpoint
        id: sed
        run: |
          set -x
          sed -i 's|http://127.0.0.1:8080|https://dungeon-sequencer-test1.gcp.marigold.dev|g' 10_dungeon/app/src/App.js
          cat 10_dungeon/app/src/App.js
          sed -i 's|http://localhost:8080|https://dungeon-sequencer-test1.gcp.marigold.dev|g' 10_dungeon/app/src/action.js
          cat 10_dungeon/app/src/action.js

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./10_dungeon/app/
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.ref == 'refs/heads/dungeon-game' }}
          tags: |
            ghcr.io/marigold-dev/dungeon-frontend:latest
            ghcr.io/marigold-dev/dungeon-frontend:${{ github.sha }}
