name: Common - docker custom rollup tezos binaries

on:
  push:
    branches:
      - "infra-main"
    paths:
      - "rollup-tezos-binaries/**"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./infra_tooling/docker/rollup-tezos-binaries/
          platforms: linux/amd64
          no-cache: true
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          # Only push if on main branch
          push: ${{ github.ref == 'refs/heads/infra-main' }}
          tags: |
            ghcr.io/marigold-dev/rollup-tezos-binaries:latest
            ghcr.io/marigold-dev/rollup-tezos-binaries:${{ github.sha }}
